#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/exynos2100

PRODUCT_COPY_FILES += \
    vendor/samsung/exynos2100/proprietary/vendor/etc/eden/gpu/eden_kernel_64.bin:$(TARGET_COPY_OUT_VENDOR)/etc/eden/gpu/eden_kernel_64.bin \
    vendor/samsung/exynos2100/proprietary/vendor/etc/gnss/gps.cer:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cer \
    vendor/samsung/exynos2100/proprietary/vendor/etc/gnss/gps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.xml \
    vendor/samsung/exynos2100/proprietary/vendor/etc/hdr_samsung_mx.key:$(TARGET_COPY_OUT_VENDOR)/etc/hdr_samsung_mx.key \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/android.hardware.keymaster@4.0_strongbox-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0_strongbox-service.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service.eden-drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service.eden-drv.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/hermesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hermesd.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/init.baseband.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.baseband.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/teegris_v4.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris_v4.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/vendor.samsung_slsi.hardware.eden_runtime@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung_slsi.hardware.eden_runtime@1.0-service.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/init/wifi_brcm.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_brcm.rc \
    vendor/samsung/exynos2100/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/exynos2100/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/exynos2100/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/exynos2100/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/exynos2100/proprietary/vendor/etc/plmn_delta_ltn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_ltn.bin \
    vendor/samsung/exynos2100/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/exynos2100/proprietary/vendor/etc/plmn_se13_prebuilt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13_prebuilt.bin \
    vendor/samsung/exynos2100/proprietary/vendor/etc/secnvm/k250a_00000304_c.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_00000304_c.img \
    vendor/samsung/exynos2100/proprietary/vendor/etc/secnvm/k250a_00000306.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_00000306.img \
    vendor/samsung/exynos2100/proprietary/vendor/etc/sensor/lhd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensor/lhd.conf \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/APBiBF_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBiBF_AUDIO_SLSI.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/bidirmic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bidirmic.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/clFGN10BitNV12_32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/clFGN10BitNV12_32.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/clFGN10BitNV12_64.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/clFGN10BitNV12_64.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/clFGN10BitYV12_32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/clFGN10BitYV12_32.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/clFGN10BitYV12_64.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/clFGN10BitYV12_64.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/clFGN8BitNV12_32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/clFGN8BitNV12_32.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/clFGN8BitNV12_64.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/clFGN8BitNV12_64.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/clFGN8BitYV12_32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/clFGN8BitYV12_32.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/clFGN8BitYV12_64.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/clFGN8BitYV12_64.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/dsp_reloc_rules.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_reloc_rules.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/libgaussian3x3.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libgaussian3x3.elf \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/libivp.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libivp.elf \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/liblog.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/liblog.elf \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/libnn.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libnn.elf \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/mfc/mfc_fw_flash.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc/mfc_fw_flash.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/exynos2100/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/exynos2100/proprietary/vendor/tee/00000000-0000-0000-0000-42494f535542:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-42494f535542 \
    vendor/samsung/exynos2100/proprietary/vendor/tee/00000000-0000-0000-0000-6d706f667376:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-6d706f667376 \
    vendor/samsung/exynos2100/proprietary/vendor/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_:$(TARGET_COPY_OUT_VENDOR)/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_ \
    vendor/samsung/exynos2100/proprietary/vendor/tee/tui/resolution_common/ID00000100:$(TARGET_COPY_OUT_VENDOR)/tee/tui/resolution_common/ID00000100

PRODUCT_PACKAGES += \
    libGLES_mali \
    audio.sec_primary.default \
    sound_trigger.primary.exynos2100 \
    vendor.samsung.hardware.audio@1.0-impl \
    vulkan.mali \
    libSamsungPostProcessConvertor \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_SRC384_ver320 \
    lib_SoundAlive_play_plus_ver500 \
    lib_soundaliveresampler \
    libalsautils_sec \
    libaudioparamupdate \
    libaudioroute_exynos2100 \
    libfloatingfeature \
    libprofileparamstorage \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecnativefeature \
    libsecril-client \
    libsehbluetooth_audio_session \
    libsemnativecarrierfeature \
    libspatializerparamstorage \
    libspeakercalibration \
    libtinyalsa_exynos2100 \
    libaudioeffectoffload \
    libmyspace \
    libplaybackrecorder \
    vendor.samsung.hardware.audio@1.0 \
    vendor.samsung.hardware.bluetooth.a2dp@1.0 \
    vendor.samsung.hardware.bluetooth.audio@2.0 \
    vendor.samsung.hardware.bluetooth.audio@2.1 \
    vendor.samsung.libcolor.hardware \
    vendor.samsung.libcolor.hdr10plus \
    vendor.samsung_slsi.hardware.ExynosA2DPOffload@3.0 \
    libaboxpcmdump \
    libaudio-ril \
    libdatamod \
    liblastaboxmsg \
    libwvhidl \
    android.hardware.gnss@2.1-impl \
    flp.default \
    gatekeeper.exynos2100 \
    gps.default \
    vendor.samsung.hardware.gnss@2.1-impl \
    libFilmGrainNoise \
    libIDDQD_core \
    libIDDQD_interface \
    libIMUSensor \
    libImageFormatConverter \
    libLocalTM_preview_core \
    libOpenCv.camera.samsung \
    libSEF.quram \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    libcommon \
    libcrane_compiler \
    libdk_vnd_service_core \
    libeden_gpu_boost_stub_vendor.edensdk.samsung \
    libeden_model \
    libeden_nn \
    libeden_nn_on_vendor \
    libeden_osal \
    libeden_profiler \
    libeden_rt \
    libeden_rt_stub_vendor.edensdk.samsung \
    libeden_ud_cpu \
    libeden_ud_dsp \
    libeden_ud_gpu \
    libeden_ud_npu \
    libeden_wrapper \
    libeden_wrapper_sdk \
    libeden_xtool \
    libeis_core \
    libengmode_client \
    libenn_dsp_dal \
    libenn_dsp_fw_graph_parser \
    libenn_dsp_kernels_cpu \
    libese-grdg \
    libexynoscamera_plugin \
    libexynoscamera_plugin_utils \
    libgraphgen_ann_import \
    libgraphgen_ann_nnc \
    libgraphgen_api \
    libgraphgen_export \
    libgraphgen_import \
    libgraphgen_intermediate_process \
    libgraphgen_misc \
    libgraphgen_network \
    libhermes \
    libhermes_bdbridge \
    libhermes_cred \
    libhwjsqz \
    libhwvault \
    libir \
    libkeymaster_helper \
    libmpbase \
    libnpu_compiler \
    libnpuc_api \
    libnpuc_backend \
    libnpuc_cmdq \
    libnpuc_common \
    libnpuc_controller \
    libnpuc_frontend \
    libnpuc_graph \
    libnpuc_template \
    libril_sem \
    libsait_npu_compiler \
    libsec-ril \
    libsec_semRil \
    libsemseg \
    libsensorlistener \
    libshctrl \
    libskeymaster4device \
    libsn100u_fw \
    libteecl \
    libuniapi \
    libuniplugin \
    libuuid_vendor \
    libvkmanager_vendor \
    libvpl \
    sensors.flicker \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.gnss@2.1 \
    vendor.samsung.hardware.hyper-V2-ndk_platform \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.security.drk@2.0 \
    vendor.samsung.hardware.thermal@1.0 \
    vendor.samsung_slsi.hardware.eden_runtime@1.0-impl \
    vendor.samsung_slsi.hardware.eden_runtime@1.0 \
    vendor.samsung_slsi.hardware.gpu_boost@1.0 \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    vendor.samsung.hardware.radio.exclude.slsi.xml \
    vendor.samsung.hardware.radio_manifest_2_34.xml \
    vendor.samsung.hardware.sehradio_manifest_2_34.xml \
    hermesd \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.keymaster@4.0_strongbox-service \
    android.hardware.neuralnetworks@1.3-service.eden-drv \
    gps \
    lhd \
    rild \
    vendor.samsung.hardware.gnss@2.1-service \
    vendor.samsung_slsi.hardware.eden_runtime@1.0-service \
    tzdaemon \
    tzts_daemon

PRODUCT_PACKAGES += \
    vendor_lib_libOpenCL_so \
    vendor_lib_libOpenCL_so_1 \
    vendor_lib_libOpenCL_so_1_1 \
    vendor_lib64_libOpenCL_so \
    vendor_lib64_libOpenCL_so_1 \
    vendor_lib64_libOpenCL_so_1_1
